### ISSUE TITLE
Setup Github wiki pages

### ISSUE THREAD

**Issue by lgblaumeiser** [lgblaumeiser/Anpfiff#4]

**Comment by davidtamayo177** [comment]
hello do you still need help on this?

**Comment by lgblaumeiser** [comment]
I would appreciate help but what do you have in mind concerning help?

**Comment by davidtamayo177** [comment]
I mean in doing wiki pages hehe

**Comment by lgblaumeiser** [comment]
Thanks, but I did some in the past :-) It is not that I do the greatest stuff in the world, that needs an awful lot of great marketing.

**Comment by davidtamayo177** [comment]
How about for the code, do you need any help? It's because I have to make a bugfix/contribution in any project as a school requirement hehe

**Comment by lgblaumeiser** [comment]
You might have a look if you find something, but I am pretty much at the start, so I do not have an idea of what could be wrong
